#!/usr/bin/env bash
# Validates a message against Conventional Commits 1.0.0.
# https://www.conventionalcommits.org/en/v1.0.0/
#
# Usage:
#   check-conventional-commit.sh "feat(api): add pagination"
#   check-conventional-commit.sh --file .git/COMMIT_EDITMSG
#
# The type list matches the `conventional-pre-commit` hook the repos run locally,
# so a message that passes the git hook passes here and vice versa.
set -euo pipefail

TYPES='build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test'

label="commit message"
message=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --file)
            message="$(head -n 1 "$2")"
            shift 2
            ;;
        --label)
            label="$2"
            shift 2
            ;;
        *)
            message="$1"
            shift
            ;;
    esac
done

# Only the first line is the subject; a body may say anything.
message="${message%%$'\n'*}"

# Merges and reverts are generated by GitHub and git, not written by a person.
if [[ "${message}" =~ ^(Merge|Revert)\  ]]; then
    exit 0
fi

# type(optional-scope)!: description
if [[ "${message}" =~ ^(${TYPES})(\([a-z0-9][a-z0-9._-]*\))?!?:\ .+ ]]; then
    exit 0
fi

cat >&2 <<MSG
✖ Not a Conventional Commit ${label}:

    ${message}

    Format:  <type>[(scope)][!]: <description>
    Types:   ${TYPES//|/, }
    Example: feat(api): add cursor pagination
             fix!: drop support for Node 18

    Spec: https://www.conventionalcommits.org/en/v1.0.0/
MSG
exit 1
